### ISSUE TITLE
[nginx_parser]	ERROR

### ISSUE THREAD

**Issue by ludovicsclain** [yandex/gixy#125]
Hi 👋 
Gixy just installed and tested and I have a NGINX-PARSER error on all my .conf file:
`[nginx_parser]	ERROR	Failed to parse config "/etc/nginx/nginx.conf": char 272 (line:3, col:1)`

`[nginx_parser]	ERROR	Failed to parse config "/etc/nginx/sites-available/my-website.conf": char 269 (line:4, col:1)`

So are the results reliables (I have no issue)?
Thanks for your help 🙏

**Comment by dzzk** [comment]
Seems it's popular buggy report. 
You will be asked for config example you not able to pass, if you check [nginx_parser] issues here.

Here is my so called buggy one:
```
upstream service-backend {
  server backend:80;
}

server {
  listen       80;
  server_name  localhost;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri /index.html;
  }
  location /api {
    proxy_pass http://ccm-backend;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Server-Proto $server_protocol;
  }
}
```

And the problem is not in upstream name, it can be just an address or name,
it seems ngx_http_upstream_module is not something acceptable here.

If I do remove upstream completely, the error will change to
`WARNING	Skip unparseable block: "server"`

And if I will take next example:
```
server {
  listen       80;
  server_name  localhost;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri /index.html;
  }
}
```

...it will also fail with warning.

I did try to change py version (2.7.17, 3.7.12) but it did not changed anything.
Wat I suppose to try - run it in a Docker image.

**Comment by thestinger** [comment]
It's broken with pyparsing > 2.4.7 so you need to use pyparsing 2.4.7.

**Comment by wedneyyuri** [comment]
> It's broken with pyparsing > 2.4.7 so you need to use pyparsing 2.4.7.

@thestinger can you guide us how?

**Comment by thestinger** [comment]
I gave you a working workaround. There's nothing else beyond that.

**Comment by wedneyyuri** [comment]
Thanks @thestinger. For a few minutes I was not sure how to do this, then it became clear that it would be as simple as manually installing the version of pyparsing.

```
pip install gixy==0.1.20 pyparsing==2.4.7
```

**Comment by Darthfett** [comment]
This should really work out-of-the-box.  Is there a clear explanation for why it doesn't (e.g. that I have a atypical config)?

My config starts with:

```
upstream backend {
    server 127.0.0.1:8080;
}
```

Fastest "fix" for me was:

```
pip uninstall pyparsing
pip install pyparsing==2.4.7
```

**Comment by thestinger** [comment]
@Darthfett pyparsing made backwards incompatible changes and unfortunately gixy isn't being actively developed at the moment.

**Comment by Darthfett** [comment]
Understood.  Backwards incompatible changes in a non-major release is unfortunate.  Opened PR 140 to address it.

Testing locally, this should install 2.4.7 as previously mentioned.

```
> pip install "pyparsing>=1.5.5,<2.5" --dry-run --ignore-installed               Collecting pyparsing<2.5,>=1.5.5
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Would install pyparsing-2.4.7
```

(or via requirements.txt):

```
> pip install -r .\requirements.txt --dry-run --ignore-installed
Collecting pyparsing<2.5,>=1.5.5 (from -r .\requirements.txt (line 1))
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting cached-property>=1.2.0 (from -r .\requirements.txt (line 2))
  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)
Collecting argparse>=1.4.0 (from -r .\requirements.txt (line 3))
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting six>=1.1.0 (from -r .\requirements.txt (line 4))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting Jinja2>=2.8 (from -r .\requirements.txt (line 5))
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting ConfigArgParse>=0.11.0 (from -r .\requirements.txt (line 6))
  Using cached ConfigArgParse-1.7-py3-none-any.whl (25 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=2.8->-r .\requirements.txt (line 5))
  Using cached MarkupSafe-2.1.3-cp311-cp311-win_amd64.whl (17 kB)
Would install ConfigArgParse-1.7 Jinja2-3.1.2 MarkupSafe-2.1.3 argparse-1.4.0 cached-property-1.5.2 pyparsing-2.4.7 six-1.16.0
```

**Comment by thestinger** [comment]
@Darthfett It was in a major release. It's pyparsing v3 and beyond that breaks it.
