### ISSUE TITLE
Licensing issue?

### ISSUE THREAD

**Issue by bobuk** [yandex/gixy#13]
Looks like you're using part of the code which is licensed with "CNRI's Python license".
I meant this [sre_parse.py](https://github.com/yandex/gixy/blob/master/gixy/core/sre_parse/sre_parse.py) file and another one in the folder.

If I remember correct, CNRI Py Li is not compatible with Mozilla License which is chosen by you for this project.

**Comment by buglloc** [comment]
I consulted with the our legal depart. and they assure me that everything was fine and CNRI Py licence are compatible with MPL-2.0.
Feel free to open issue if i'm wrong:)
