### ISSUE TITLE
Ошибка при установки (Debian 8 x64)

### ISSUE THREAD

**Issue by simvolice** [yandex/gixy#17]
![default](https://cloud.githubusercontent.com/assets/5946300/25541985/881714ec-2c72-11e7-8625-5495ea4114d3.JPG)

**Comment by buglloc** [comment]
Я думаю это проблема на стороне pip, а не gixy.

Судя по стектрейсу pip не может подключиться к PyPi.
Есть ли что-то интересное в `/root/.pip/pip.log`?
Есть ли доступ в интернет на машинке, где вы пробуете установить Gixy?
Можете ли вы curl'ом запросить информацию о пакете `curl https://pypi.python.org/pypi/gixy/json`?

**Comment by simvolice** [comment]
Curl'ом пробивается, все ок. В логах pip'a тоже самое:

Downloading/unpacking gixy
  Getting page https://pypi.python.org/simple/gixy/
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 194, in find_requirement
    page = self._get_page(main_index_url, req)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 694, in get_page
    req, link, "connection error: %s" % exc, url,
TypeError: __str__ returned non-string (type SysCallError)

**Comment by gongled** [comment]
Предположу, что проблема локальная и связана с SSL/TLS (например, с python-certifi), а не с `gixy`. Для сравнения, в Docker-контейнере с Debian Jessie всё в порядке:
```
$ docker run --rm -it debian:8 bash
root@37b9792c0e90:/# apt-get -qq update > /dev/null && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq python-dev python-pip > /dev/null
root@37b9792c0e90:/# dpkg -s python-pip | grep Version
Version: 1.5.6-5
root@37b9792c0e90:/# pip install gixy
Downloading/unpacking gixy
  Downloading gixy-0.1.1-py2.py3-none-any.whl (44kB): 44kB downloaded
Requirement already satisfied (use --upgrade to upgrade): six>=1.1.0 in /usr/lib/python2.7/dist-packages (from gixy)
[...]
Successfully installed gixy cached-property ConfigArgParse Jinja2 pyparsing argparse MarkupSafe
Cleaning up...
root@37b9792c0e90:/# gixy --version
Gixy v0.1.1
```

**Comment by buglloc** [comment]
Полагаю issue можно закрывать, т.к. эта проблема установки не связана с `gixy`.
