### ISSUE TITLE
Allow processing stdin, file descriptors

### ISSUE THREAD

**Issue by bennullgraham** [yandex/gixy#32]
With gixy installed locally, it would be nice to check config on remote machines like:

```
gixy <(ssh remote-host cat /etc/nginx/...)
```

The handling of the `nginx_file` argument (e.g. `os.path.isfile` check) means this doesn't work. Perhaps use the python `fileinput` module to handle the file? There is an example of argparse+fileinput here: https://gist.github.com/martinth/ed991fb8cdcac3dfadf7https://gist.github.com/martinth/ed991fb8cdcac3dfadf7

**Comment by buglloc** [comment]
Must be introduced in Gixy v0.1.4. Feel free to open issue if something go wrong:)
