### ISSUE TITLE
Breaks when upstream name contains a period

### ISSUE THREAD

**Issue by andreparames** [yandex/gixy#35]
This excerpt of a config file:

    upstream ex.ample {
        server 127.0.0.1:9002;
    }

Produces the following error:
`[nginx_parser]	ERROR	Failed to parse config "nginx.conf": Expected ";" (at char 18), (line:1, col:19`

I'm not sure if a period is technically allowed, but Nginx parses them just fine :)

**Comment by royaldark** [comment]
I am also experiencing this, but I get a much longer error.

```
upstream test.mysite.com {
    server 127.0.0.1:9009;
}
```
gives

`[nginx_parser]	ERROR	Failed to parse config "test.mysite.com.conf": Expected {Forward: ... | Forward: ... | Forward: ... | Forward: ... | {"include" Suppress:(<SPC><TAB><CR><LF>) {quoted string, starting with " ending with " | quoted string, starting with ' ending with ' | Re:('(?:\\([^\\s;]*\\)|\\$\\{\\w+\\}|[^\\s;(){}])+')} Suppress:(";")} | {W:(ABCD...) [{Suppress:(<SPC><TAB><CR><LF>) {quoted string, starting with " ending with " | quoted string, starting with ' ending with ' | Re:('(?:\\([^\\s;]*\\)|\\$\\{\\w+\\}|[^\\s;(){}])+')}}]... Suppress:(";")} | {Suppress:("# configuration file ") W:(ABCD...) Suppress:(":")} | Re:('#.*') | Forward: ...} (at char 25), (line:1, col:26)`

**Comment by buglloc** [comment]
Thanks! Fixed in Gixy v0.1.4
