### ISSUE TITLE
[request] nginx root directory

### ISSUE THREAD

**Issue by dynek** [yandex/gixy#45]
Hello,

I'm not a Python savvy otherwise I would have proposed a PR (might come if no one else judge it useful).
I'd like to be able to verify a configuration before it lands into Kubernetes/Configmap.
Files could be moved to /etc/nginx prior to running gixy but in the current state if I test a file in /a/b/c/nginx.conf that includes other files, it will fail saying "[nginx_parser]  WARNING File not found: /etc/nginx/conf.d/internal.conf".
It's not looking for that "conf.d/internal.conf" file inside the directory I'm currently located (or based on the path to nginx.conf but straight into /etc/nginx which doesn't exist.

Thank you

**Comment by buglloc** [comment]
Hello,

Let's see what behavior you would like to see. For example, we have config with several includes (relative and absolute):
```nginx
$ cat /tmp/test/nginx.conf
user http;
worker_processes  1;
daemon off;

events {
    worker_connections  1024;
}

http {
    include mime.types;
    include conf.d/*.conf;
    include /tmp/another/some.conf;
}
```

For now Gixy use directory of `nginx.conf` as a root directory and try to resolve any relative included files from it, e.g.:
```
$ gixy -d /tmp/test/nginx.conf
[main]	DEBUG	logging initialized
[manager]	DEBUG	Audit config file: /tmp/test/nginx.conf
[nginx_parser]	DEBUG	Parse file: /tmp/test/mime.types
[nginx_parser]	DEBUG	Parse file: /tmp/test/conf.d/headers.conf
[nginx_parser]	DEBUG	Parse file: /tmp/another/some.conf
```

That you want to change in this logic? Resolve files based on `nginx.conf` placement and current directory?

**Comment by dynek** [comment]
Hello @buglloc - I thought the root path was not determined based on nginx.conf location.
But that was (shame on me) because of an absolute lying around :-(

Sorry for the noise.
