### ISSUE TITLE
Plugin - Misconfigure Alias Caused Path Traversal 

### ISSUE THREAD

**Issue by phith0n** [yandex/gixy#61]
For example:

```
location /files {
    alias /home/;
}
```

At the context,  we can access files and directories that are stored outside path `/home/`, such as `http://example.com/files../etc/passwd`

![image](https://user-images.githubusercontent.com/5711185/26842217-9b7efc00-4b1e-11e7-8cd4-015e54a4a5a1.png)

**Comment by buglloc** [comment]
Hi! Thanks:)
I added the new plugin, it checks that prefix location must ends with `/` if `alias` directive used.
E.g.:
  - correct:
```nginx
location /files/ {
    alias /home/;
}
```
  - incorrect:
```nginx
location /files {
    alias /home/;
}
```
