### ISSUE TITLE
Problem: [origins] Validation regex for "origin" or "referrer" matches untrusted domain.

### ISSUE THREAD

**Issue by detailyang** [yandex/gixy#65]
Hello. I'm curious the question about CORS

```nginx
if ($http_origin ~* ((^https://www\.yandex\.ru)|(^https://ya\.ru)/)) {
	add_header 'Access-Control-Allow-Origin' "$http_origin";
	add_header 'Access-Control-Allow-Credentials' 'true';
}
```

The Host Header ABNF is as the following [whatwg](https://fetch.spec.whatwg.org/#origin-header) or [rfc6454](https://tools.ietf.org/html/rfc6454#section-7):
```
Origin                           = origin-or-null

origin-or-null              = origin / %x6E.75.6C.6C ; "null", case-sensitive
origin                           = scheme "://" host [ ":" port ]
```

The origin does not reveal a path. So use regex pattern `^` and `$` is enough in my option. Are there any browser will include the path when send a ajax?

**Comment by alexeyten** [comment]
Your regexp allows `https://www.yandex.ru.evil.com` origin

**Comment by buglloc** [comment]
You are right, I was wrong :) A while ago I met the path inclusion to the Origin, but it was probably a browser specific bug.

I changed regex in documentation to:
```(regex)
((^https://www\.yandex\.ru)|(^https://ya\.ru)$)
```
